base_model_id: google/gemma-3-4b-it
dataset_id: nvidia/OpenCodeInstruct
dataset_subset: train
docker_image: halez/lora-finetuner:latest
gpu_name: H100 NVL
hf_token: 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
lora_model_repo: hamzafaisal/google/gemma-3-4b-it-lora
max_train_steps: 100
num_gpus: 1
