base_model_id: mistralai/Mistral-7B-Instruct-v0.3
dataset_id: nvidia/OpenCodeInstruct
dataset_subset: train
docker_image: halez/lora-finetuner:latest
gpu_name: H100 NVL
hf_token: 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
lora_model_repo: hamzafaisal/mistralai/Mistral-7B-Instruct-v0.3-lora
max_train_steps: 100
num_gpus: 1
