base_model_id: openai/gpt-oss-20b
dataset_id: nvidia/OpenCodeInstruct
dataset_subset: train
docker_image: halez/lora-finetuner:latest
gpu_name: H200 NVL
hf_token: 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
lora_model_repo: hamzafaisal/openai/gpt-oss-20b-lora
max_train_steps: 100
num_gpus: 1
