base_model_id: distilgpt2
dataset_id: fka/awesome-chatgpt-prompts
dataset_subset: default
docker_image: halez/lora-finetuner:latest
gpu_name: H100 NVL
hf_token: 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
lora_model_repo: hamzafaisal/distilgpt2-lora
max_train_steps: 100
num_gpus: 1
